### ISSUE TITLE
issue on Dependency Walker description

### ISSUE THREAD

**Issue by BaeMinCheon** [MicrosoftDocs/cpp-docs.ko-kr#63]
The "Dependency Walker" is not compatible after Windows 10. Thus, I suggest to mention about the incompatibility or to give some tools for Windows 10 user.

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: d0582c64-876f-0044-e004-feaca588d7cb
* Version Independent ID: ca607a95-94bb-e162-2b77-828e5acbc5ed
* Content: [Visual C++ 응용 프로그램의 종속성 이해](https://docs.microsoft.com/ko-kr/cpp/ide/understanding-the-dependencies-of-a-visual-cpp-application?view=vs-2017)
* Content Source: [docs/ide/understanding-the-dependencies-of-a-visual-cpp-application.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/ide/understanding-the-dependencies-of-a-visual-cpp-application.md)
* Product: **visual-cpp**
* GitHub Login: @corob-msft
* Microsoft Alias: **corob**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/cpp-docs #514](https://github.com/MicrosoftDocs/cpp-docs/issues/514) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @BaeMinCheon ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/cpp-docs/issues/514.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
