### ISSUE TITLE
It's not a big problem but the bracket is wrong

### ISSUE THREAD

**Issue by wooPedia** [MicrosoftDocs/cpp-docs.ko-kr#939]
[여기에 피드백 입력]
It's not a big problem but the bracket is wrong. I think It should be a '{' not a '('. 
Ctrl + F -> class_d d5("string", 'c', 2.0 }; // compiler error

---
#### 문서 세부 정보

⚠ *이 섹션을 편집하지 마세요. docs.microsoft.com ➟ GitHub 문제 연결에 필요합니다.*

* ID: 441b3ef5-7a22-0496-ddec-6baee7262991
* Version Independent ID: 711a8364-a43c-22fc-217a-30c95c5c946b
* Content: [클래스, 구조체 및 공용 구조체에 대 한 중괄호 초기화](https://docs.microsoft.com/ko-kr/cpp/cpp/initializing-classes-and-structs-without-constructors-cpp?view=vs-2019#feedback)
* Content Source: [docs/cpp/initializing-classes-and-structs-without-constructors-cpp.md](https://github.com/MicrosoftDocs/cpp-docs.ko-kr/blob/live/docs/cpp/initializing-classes-and-structs-without-constructors-cpp.md)
* Product: **visual-cpp**
* Technology: **cpp-language**
* GitHub Login: @mikeblome
* Microsoft Alias: **mblome**

**Comment by srvbpigh** [comment]
Hello, @wooPedia
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by drvoss** [comment]
@wooPedia @srvbpigh @CeciAc
I have a fix in PRs #939. fix typo.

**Comment by CeciAc** [comment]
Hello, @wooPedia 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/MicrosoftDocs/cpp-docs.ko-kr/issues/939
For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
